### ISSUE TITLE
[Bug] Cannot progress with starting main quest

### ISSUE THREAD

**Issue by Nephiro** [Hartie95/Grasscutter#50]
When you arrive to the Seven Statue with the main quest at the very beginning, after talking with Paimon and get Anemo power you have to defeat slimes. Even before reaching the Statue there are lots of phyro slimes (some even lv 10). I defeat them throwing in the water, the quest doesn't go on. It still ask me to defeat slimes.

![immagine](https://user-images.githubusercontent.com/19551224/210574499-6e79ef7a-630a-4c4a-9489-4fad713f3b98.png)

I tried to log-out and login again, the slime spawn again, I defeat them again, still nothing.

I tried this with last commit that implements 3.2 and even with older ones. I even tried with mjolsic branch, the same thing.

I'm using 3.1 resources with 3.2 game (before the recent commit I used 3.1 game version).

On the console I get these warning every login.

![immagine](https://user-images.githubusercontent.com/19551224/210575297-bba5bf9b-b19f-4d11-8a1c-5a5116e29097.png)

Every try I made I always cleaned the branch, mean deleted old one, download new one, compile, new db. Every time the same result in that point and I cannot go on.

I know I can always complete the quest with the command, but since this fork is made to make the main quest works I wanted to report and ask for a solution. Maybe I'm doing something wrong.

Dunno if this is helpful or not, but the first time I start with a new account I get these errors on the console

![immagine](https://user-images.githubusercontent.com/19551224/210576547-3e5d0991-f3dc-446a-8a7a-a74f7dfce7a6.png)

Maybe it's because of that missing trigger 1101?

**Comment by mjolsic** [comment]
Did you enable big script world in config.json?

**Comment by Nephiro** [comment]
Ok, my fault. I forgot to enable that one...... Sorry and thanks for the help 👍
